# Generated by Django 5.1.3 on 2024-11-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_ped', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('id_clien', models.CharField(max_length=10)),
                ('id_emp', models.CharField(max_length=10)),
                ('id_prod', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
            ],
        ),
    ]
