# Generated by Django 5.1.3 on 2024-11-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_prod', models.CharField(max_length=10)),
                ('id_emp', models.CharField(max_length=10)),
                ('id_clien', models.CharField(max_length=10)),
            ],
        ),
    ]
