# Generated by Django 5.1.3 on 2024-11-23 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='id_prod',
            new_name='id_prov',
        ),
    ]
